# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bac1d6500166cc10232b2754f7b956b954194b0371283c9d7802c191ce66e0887a8ec5e58bdc126715085c55a48aa20d1bd959af80c35a18c04993657f29765

test:
  secret_key_base: ed6240932a5ea63826dede3f28e01c0eb483d6a2cd06ac03745c0284b183915d3313f471a82d4a1d5de543b3f0c98ce6d9aa11578daa20d37e17fe4326f1d750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
